CREATE DATABASE BDEstoque;

GO

USE BDEstoque;

CREATE TABLE TBFornecedor(
	ID			INT IDENTITY,
	NOME		VARCHAR(50) NOT NULL,
	CNPJ		CHAR(14)	NOT NULL,
	ENDERECO	VARCHAR(50),
	CONSTRAINT PK_FORNECEDOR PRIMARY KEY(ID),
	CONSTRAINT UQ_FORNECEDOR_CNPJ UNIQUE(CNPJ)
);

select * from TBFornecedor;

CREATE TABLE TBProduto(
	ID				INT IDENTITY,
	DESCRICAO		VARCHAR(30) NOT NULL,
	QUANTIDADE		INT,
	VALOR_UNIT		MONEY,
	ID_FORNECEDOR	INT NOT NULL,
	CONSTRAINT PK_PRODUTO PRIMARY KEY(ID),
	CONSTRAINT CK_PRODUTO_QUANTIDADE CHECK(QUANTIDADE >=0),
	CONSTRAINT CK_PRODUTO_VALOR_UNIT CHECK(VALOR_UNIT >=0),
	CONSTRAINT FK_PRODUTO_FORNECEDOR FOREIGN KEY (ID_FORNECEDOR) REFERENCES TBFornecedor(ID)
);

select * from TBProduto;

CREATE TABLE TBUsuario(
	USUARIO			VARCHAR(30),
	SENHA			VARCHAR(32)	NOT NULL,
	NOME_USUARIO	VARCHAR(50)	NOT NULL,
	TIPO_USUARIO	INT			NOT NULL	DEFAULT 0,
	CONSTRAINT PK_USUARIO PRIMARY KEY(USUARIO),
	-- 0 => USUARIO / 1 => ADMINISTRADOR
	CONSTRAINT CK_TIPO_USUARIO CHECK((TIPO_USUARIO = 0) OR (TIPO_USUARIO = 1))
);

insert into TBUsuario(USUARIO, SENHA, NOME_USUARIO, TIPO_USUARIO) values ('admin','123456','Paulo', 1);

select * from TBUsuario;